version: "3"
services:
  app:
    container_name: app
    restart: always
    build:
      dockerfile: Dockerfile.prod
      context: .
    ports:
      - "3000:3000"
  mongo:
    image: mongo
    volumes:
      - /data/mongodb/db:/data/db
    ports:
      - "27017:27017"
